# Generated by Django 4.0.5 on 2022-06-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_stock_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aviable',
            field=models.BooleanField(default=True),
        ),
    ]
