# Generated by Django 4.0.5 on 2022-06-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_aviable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(default='unit', max_length=50, null=True),
        ),
    ]
