# Generated by Django 4.0.5 on 2022-06-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_order_cart_rename_orderproduct_cartproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_date',
            new_name='cart_date',
        ),
    ]
