# Generated by Django 4.0.5 on 2022-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cart_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
