# Generated by Django 4.0.5 on 2022-06-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cart_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
