# Generated by Django 4.0.5 on 2022-06-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_cartitem_product_delete_cart_delete_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',)},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
